# Dockerfile-linphone
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
  linphone \
  pulseaudio \
  x11-utils \
  && rm -rf /var/lib/apt/lists/*

CMD ["linphone"]

